#!/usr/bin/env bash
#
#/ AeroDict - Aviation abbreviations and acronyms dictionary.
#/
#/ Usage: aerodict [OPTIONS]
#/
#/ OPTIONS:
#/
#/   General options:
#/
#/       -h, -?, --help                   - Print this help text and exit
#/       -v, --version                    - Print program version and exit
#/
# commander is under a MIT style licence.
# See LICENSE.md for the full text.
#
# This is open source! Please feel free to contribute.
# https://github.com/SiteNetAviation/AeroDict/

# Initial setup
VERSION="1.0.0"
CONFIG_FILE="config/config.csv"

# Print help text extracted from comments
print_help() {
    grep '^#/' "$0" | cut -c 4-
}

# Print version information
print_version() {
    echo "AeroDict version $VERSION"
}

# Parse command-line options
while (( "$#" )); do
    case "$1" in
        -v|--version)
            print_version
            exit 0
            ;;
        --) # End of all options
            shift
            break
            ;;
        -h|--help|-?|--\?)
            print_help
            exit 0
            ;;
        -*|--*=) # Unsupported flags
            echo "Error: Unsupported flag $1" >&2
            exit 1
            ;;
        *) # Unrecognized arguments
            echo "Error: Unrecognized argument $1" >&2
            exit 1
            ;;
    esac
done

# Function to display sources for selection
#display_sources_for_selection() {
#    local content=$(cat "$CONFIG_FILE" | csvquote)
    #local content=$(cat "$CONFIG_FILE" | sed 's/"//g') # Remove quotes
#    echo "$content" | awk -F',' '{print $1 ", " $3 ", " $2}' | column -t -s ','
#}

# Function to display sources for selection
display_sources_for_selection() {
    #local content=$(csvquote < "$CONFIG_FILE")
    #echo "$content" | awk -F',' '{print $1, $3, $2}' | column -t -s ','
    #cat "$CONFIG_FILE" | csvquote | awk -F',' -v OFS=',' '{print $1, $3, $2}' | csvquote -u
    awk -v FPAT='([^,]+)|(\"[^\"]+\")' -v OFS=',' '{print $1, $3, $2}' "$CONFIG_FILE" | column -t -s ','
}

# Function to load and present data from selected CSV
#load_and_present_data() {
#    local selected_source_file="config/$1.csv"
    
#    if [[ ! -f "$selected_source_file" ]]; then
#        echo "Error: Data file $selected_source_file not found" >&2
#        exit 1
#    fi

#    cat "$selected_source_file" | awk -F',' '{gsub(/"/, "", $1); gsub(/"/, "", $2); printf "%-15s %s\n", $1, $2}' | fzf --ansi --preview-window=hidden:wrap
#}

# Function to load and present data from selected CSV
#load_and_present_data() {
#    local selected_source_file="config/$1.csv"
    
#    if [[ ! -f "$selected_source_file" ]]; then
#        echo "Error: Data file $selected_source_file not found" >&2
#        exit 1
#    fi

    # Use csvquote to manage special characters, including handling of escaped double quotes
#    cat "$selected_source_file" | csvquote | awk -F',' '{gsub(/""/, "\"", $2); printf "%-15s %s\n", $1, $2}' | csvquote -u | fzf --ansi --preview-window=hidden:wrap
#}

# Function to load and present data from selected CSV
#load_and_present_data() {
#    local selected_source_file="config/$1.csv"
    
#    if [[ ! -f "$selected_source_file" ]]; then
#        echo "Error: Data file $selected_source_file not found" >&2
#        exit 1
#    fi

#    awk -v FPAT='([^,]+)|(\"[^\"]+\")' -v OFS=',' '{ 
#        $1=$1;  # This is to rebuild the $0 with OFS as the separator
#        gsub(/^"|"$/, "", $1);  # Strip the leading and trailing quote from the first field
#        gsub(/""/, "\"", $2);  # Replace escaped quotes with a single quote in the second field
#        print $1, $2 
#    }' "$selected_source_file" | fzf --ansi --preview-window=hidden:wrap
#}

# Function to load and present data from selected CSV
load_and_present_data() {
    local selected_source_file="config/$1.csv"
    
    if [[ ! -f "$selected_source_file" ]]; then
        echo "Error: Data file $selected_source_file not found" >&2
        exit 1
    fi

    # Process the CSV file
#    awk -v FPAT='([^,]+)|(\"[^\"]+\")' '{ 
#        for (i = 1; i <= NF; i++) {
            # Remove leading and trailing quotes from each field
#            gsub(/^"|"$/, "", $i);
#            # Replace escaped quotes with a single quote
#            gsub(/""/, "\"", $i);
#        }
#        # Print all fields, separated by a comma
#        $1 = $1; # This forces awk to re-construct the record with the new field separators
#        print
#    }' "$selected_source_file" | column -t -s ',' | fzf --ansi --preview-window=hidden:wrap

#	awk -v FPAT='([^,]+)|(\"[^\"]+\")' '{
#	    for (i = 1; i <= NF; i++) {
#		gsub(/^"|"$/, "", $i);  # Remove leading and trailing quotes
#		gsub(/""/, "\"", $i);   # Replace escaped double quotes with single quotes
#	    }
#	    print $0;  # Print the whole record
#	}' "$selected_source_file"

	awk -v FPAT='([^,]*)|("[^"]+")' '{
	    for (i = 1; i <= NF; i++) {
		# Remove leading and trailing quotes from each field
		gsub(/^"|"$/, "", $i);
		# Replace escaped double quotes with a single quote
		gsub(/""/, "\"", $i);
	    }
	    # Print the fields without quotes, separated by a space or other delimiter
	    print $1, $2, $3
	}' "$selected_source_file"

}

# Main function
main() {
    local selection=$(display_sources_for_selection | fzf --ansi --preview-window=hidden:wrap)
    local selected_file=$(echo "$selection" | awk '{print $NF}')

    if [ -n "$selected_file" ]; then
        load_and_present_data "$selected_file"
    fi
}

# Execute main if script is not being sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
