.TH aerodict 1 "2024-03-03" "aerodict 1.0.0" "User Commands"
.SH NAME
aerodict \- tool for looking up aviation abbreviations and acronyms
.SH SYNOPSIS
.B aerodict
.RI [ options ]
.SH DESCRIPTION
.PP
Tool for looking up aviation abbreviations and acronyms.
.SH OPTIONS
.TP
.B \-h, \-\-help
Display help message.
.TP
.B \-v, \-\-version
Display version information.
.SH FILES
.TP
.I /usr/local/share/aerodict/config
Configuration and data files.
.SH AUTHOR
Written by Jean-Nicolas Boulay Desjardins.
