#!/usr/bin/env bash

# Define URL and output file
url="https://www.faa.gov/jobs/abbreviations"
outputFile="config/faa_acronyms_and_abbreviations.csv"

# Fetch the webpage content
content=$(wget --header="Accept-Encoding: gzip, deflate, br" \
     --header="Accept-Language: en-US,en;q=0.5" \
     --header="DNT: 1" \
     --header="Connection: keep-alive" \
     --header="Upgrade-Insecure-Requests: 1" \
     --header="Sec-Fetch-Dest: document" \
     --header="Sec-Fetch-Mode: navigate" \
     --header="Sec-Fetch-Site: none" \
     --header="Sec-Fetch-User: ?1" \
     --header="Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8" \
     --header="User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0" \
     -O - "$url" | gunzip -c)

# Preprocess the content to remove <abbr> tags while keeping their content
processedContent=$(echo "$content" | sed 's/<abbr>//g; s/<\/abbr>//g')

# Process and extract relevant data
echo "$processedContent" | pup 'main#main article section div.card div.card-block dl json{}' | \
jq -r '.[] | .children | .[] | select(.tag == "dt" or .tag == "dd") | 
(if .tag == "dt" then (if .children[0]? then .children[0].text else .text end) else .text end) |
gsub("&nbsp;"; " ") | gsub("<[^>]*>"; "")' | \
perl -MHTML::Entities -lpe 'decode_entities($_);' | \
paste -d, - - | \
awk -F',' '{print "\"" $1 "\",\"" $2 "\""}' > "$outputFile"

echo "Data extracted to $outputFile"
